# Generated by Django 5.1.6 on 2025-02-11 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blo', '0003_vlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='blogimg')),
                ('description_big', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blo.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blo.category')),
                ('tag', models.ManyToManyField(to='blo.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Vlog',
        ),
    ]
