# Generated by Django 5.1.6 on 2025-02-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blo', '0005_alter_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tag',
            new_name='tags',
        ),
    ]
